### ISSUE TITLE
Feature Request: allow SSL connections through server-side proxy

### ISSUE THREAD

**Issue by shubha-rajan** [tlocke/pg8000#61]
We're working on integrating this driver with a [connector for Google Cloud SQL](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector) and an issue that we're running into is that the following code for requesting SSL fails because we're connecting to a server side proxy instead of directly to Postgres.
```
                    self._usock.sendall(ii_pack(8, 80877103))
                    resp = self._usock.recv(1)
                    if resp != b'S':
                        raise InterfaceError("Server refuses SSL")
```
Adding a flag to the connection initialization parameters to optionally disable this block would solve the problem.

**Comment by tlocke** [comment]
Hi @shubha-rajan I've used your patch in: https://github.com/tlocke/pg8000/commit/37dcbe32bc6703dbacebd8f0d8ec94cad946fda7 I've reworked it a bit, hope that's okay :-) The first thing is that we now support channel binding for SCRAM authentication, which can only be used if there's a direct connection SSL connection to the PostgreSQL server. So in the case of a proxy we just use the non-channel-binding variant if we're using SCRAM. The other thing is that I've taken the approach of adding a custom attribute `ssl.SSLContext.request_ssl` to hold the flag, rather than having a separate connection parameter. My thinking is that this is simpler for users. Anyway, hope you like it! I'll close the issue now, but feel free to open it again if something's not right.
